services:
  - type: web
    name: ingredient-insights-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn chatbackend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbackend.settings_production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
